# Generated by Django 6.0.7 on 2026-08-12 21:26

import armario.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('camisa', 'Camisa'), ('pantalon', 'Pantalon'), ('zapatos', 'Zapatos'), ('cabello', 'Cabello'), ('cara', 'Cara'), ('accesorios', 'Accesorios')], max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParteRopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preview', 'Preview'), ('torso', 'Torso'), ('manga', 'Manga'), ('puesto', 'Puesto')], max_length=50)),
                ('imagen', models.ImageField(upload_to=armario.models.ropa_imagen)),
                ('ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes_ropa', to='armario.ropa')),
            ],
        ),
        migrations.CreateModel(
            name='Outfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ropa', models.ManyToManyField(related_name='outfits', to='armario.ropa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nombre'), name='unico_nombre_outfit')],
            },
        ),
        migrations.CreateModel(
            name='RopaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
                ('ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armario.ropa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ropa'), name='unico_usuario_ropa')],
            },
        ),
    ]
