# Generated by Django 6.0.7 on 2026-08-12 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RopasEquipadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ropausuarios',
            name='unico_usuario_ropa',
        ),
        migrations.AddField(
            model_name='ropasequipadas',
            name='ropa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armario.ropa'),
        ),
        migrations.AddField(
            model_name='ropasequipadas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ropas_equipadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ropausuarios',
            name='ropa',
        ),
        migrations.RemoveField(
            model_name='ropausuarios',
            name='usuario',
        ),
        migrations.AddConstraint(
            model_name='ropasequipadas',
            constraint=models.UniqueConstraint(fields=('usuario', 'ropa'), name='unico_usuario_ropa'),
        ),
        migrations.DeleteModel(
            name='RopaUsuarios',
        ),
    ]
